# モジュールの使い方

## モジュールのインポート

Pythonでは特別な関数や値をまとめたものをモジュールと呼び、これらを他のスクリプトで
呼び出すために`import`という文を使う。
以下のように宣言する。
```
import モジュール名
```
`import`で呼び出した後`モジュール名.モジュールの中での関数名`で機能を利用することができる。
複数のモジュールをカンマで区切って同時にインポート出来る。

In [4]:
import math

print(math.sqrt(2))
print(math.pi)
print(math.sin(math.pi/4))
print(math.cos(0))
print(math.log(32,2)) #２を底とする32の対数

1.4142135623730951
3.141592653589793
0.7071067811865475
1.0
5.0


## from

モジュール内で定義されている関数を「モジュール内で定義されている関数名」のようにして、
「モジュール名.」をつけずにそのままの名前で利用したい時は`from`を使ってインポートする。

```
from モジュール名 import モジュール内での関数名
```

In [17]:
from math import sqrt
print(sqrt(2))
from math import pi
print(pi)
from math import sin
print(sin(2))
from math import cos
print(cos(0))
from math import log
print(log(1024, 2))

1.4142135623730951
3.141592653589793
0.9092974268256817
1.0
10.0


ワイルドカードを用いて明示的に指定せず、アンダーバーで始まるモノ以外すべてを読み込む方法もあるが
モジュール内の未知の関数とプログラム内の自身で定義した名前と衝突する可能性があるため推奨されていない。
```
from モジュール名 import *
```


In [19]:
from math import *
print(factorial(5)) # 階乗
print(floor(2.31)) # 2以下の最大の整数
print(e) # 自然対数

120
2
2.718281828459045


In [21]:
# 衝突の例・自身で定義した変数が上書きされる
pi = 'パイ'
print(pi)
from  math import *
print(pi)

パイ
3.141592653589793


## as
モジュール名が長すぎるなどの理由から別名を定義したい場合は`as`を利用することができる。
例えば`Numpy`を`np`という略称で使うことがある。

In [3]:
import numpy
print(numpy.ones((3, 5))) # 3×5の正方行列
import numpy as np
print(np.ones((3,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


個々の関数に別の名前を命名することも出来る。


In [5]:
import math
print(math.factorial(5)) # ５の階乗
from math import factorial as fact
print(fact(5))

120
120
