# Numpy

Numpyとは多次元配列を効率的に扱うためのライブラリである。
標準ライブラリではないが、科学技術計算や機械学習など、ベクトル、行列演算が多用される
分野ではデファクトスタンダードとなっている。


In [1]:
# インポート・別名でnpとして利用されることが多い
import numpy as np

## 配列の構築
配列とは特定の型の値の並びである。
要素が同じであればリストやタプル、どちらを用いても同じ配列（というデータ型）を作ることが出来る。

In [2]:
a = np.array([1,2,3])
print(a)
b = np.array((1,2,3))
print(b)
c = type(a)  # 配列はnumpy.ndarrayというデータ型となっている
print(c)

[1 2 3]
[1 2 3]
<class 'numpy.ndarray'>


## 構成する要素の型

| 型名 | 説明 |
|:---|:---|
|numpy.int32|整数(32-bit)を表す|
|numpy.float64|実数(64-bit)を表す|
|numpy.complex128|複素数(64-bit実数の組)を表す|
|numpy.bool|真理値を表す型|

リストとは異なり、異なる型の値を混在させることはできない。
arrayのdtype引数に要素の型を表すオブジェクトや文字列を与えることで、任意の型の配列を作ることが出来る。

In [3]:
print(np.array([-1,0,1], dtype=np.int32)) # int32でも可

print(np.array([-1,0,1], dtype=np.float64)) # float64でも可

print(np.array([-1,0,1], dtype=np.complex128)) # complex128でも可

print(np.array([-1,0,1], dtype=np.bool)) #boolでも可

[-1  0  1]
[-1.  0.  1.]
[-1.+0.j  0.+0.j  1.+0.j]
[ True False  True]


## 多次元配列


In [4]:
print(np.array([[1,2], [3,4]])) # 二次元配列

print(np.array([[[1,2],[3,4]],[[5,6],[7,8]]])) # 三次元配列

[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


配列の長さが等しくない場合、多次元配列とは見做されず、リストの配列として扱われる。
多次元配列の各次元の長さの組を、形(shape)と呼び、数学の行列と同じように行×列で表す。


In [5]:
# 一次元配列を多次元配列に変換する・reshape()メソッド

a1 = np.array([0,1,2,3,4,5])
a2 = a1.reshape(2,3)
print(a2)

[[0 1 2]
 [3 4 5]]


In [6]:
# reshapeを適用する前後の配列は内部的にデータを共有している
a1[1] = 6
print(a1)
print(a2)

[0 6 2 3 4 5]
[[0 6 2]
 [3 4 5]]


In [7]:
# ravel()メソッドで多次元配列を一次元配列に戻す・こちらも内部的にデータを共有している
a = np.array([0,1,2,3,4,5]).reshape(2,3)
print(a)
print(a.ravel())

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


## 配列のデータ属性

|属性|意味|
|:---|:---|
|a.dtype|配列`a`の要素型|
|a.shape|配列`a`の形|
|a.nidm|配列`a`の次元数(`len(a.shape)`に等しい|
|a.size|配列`a`の要素数(`a.shape`の総乗と等しい|
|a.flat|配列`a`の1次元表現(`a.ravel()`と等しい|
|a.T|配列`a`を転置した配列(`a`と要素を共有)|

## 配列要素を生成する構築関数

要素を生成して配列を構築する代表的な関数。
特に断りがない場合は、`array()`と同様に`dtype`引数で要素型を」指定できる。


In [11]:
# arange・rangeの配列版
print(np.arange(3))
print(np.arange(0, 1, 0.2))

[0 1 2]
[0.  0.2 0.4 0.6 0.8]


In [16]:
# linspace
# 範囲を等分割した値からなる配列を生成する。
# 第一引数と第二引数にそれぞれ始点と終点、第三引数に分割数を指定する

print(np.linspace(0, 1, 10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [19]:
# zeros・0からなる配列を生成する
print(np.zeros(4)) # 長さ4の一次元配列
print(np.zeros((2,3))) # 2×３の二次元配列

# ones・1からなる配列を生成する
print(np.ones(3))
print(np.ones((2,3)))

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [28]:
# ranodm.rand・0以上1未満の乱数からなる配列を生成する
print(np.random.rand(4))
print(np.random.rand(2,3))
print(np.random.randn(4)) # 正規分布
print(np.random.binomial(10,0.2)) # 二項分布
print(np.random.poisson(4)) # ポアソン分布

[0.26107084 0.65788328 0.27369727 0.9325986 ]
[[0.9654809  0.26009111 0.61406049]
 [0.65740066 0.12906595 0.69960188]]
[ 0.9835413  -1.35864549 -0.78462651  0.23227359]
4
6


In [23]:
def range_square_matrix(n):
    return np.array([np.arange(i, n+i) for i in range(n)])

In [24]:
range_square_matrix(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])